name: Post Scores to Slack

on:
  workflow_dispatch:
  # Triggers the workflow on a weekly schedule using cron syntax
  #           ┌───────────── minute (0 - 59)
  #           │ ┌───────────── hour (0 - 23)
  #           │ │ ┌───────────── day of the month (1 - 31)
  #           │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #           │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #           │ │ │ │ │
  #           │ │ │ │ │
  #           │ │ │ │ │
  #           * * * * *
  schedule:
    - cron: '0 7 * 1,9-12 2'  # Tuesdays at 07:00

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      run: python3 sleeper_matchup_bot.py ${{ secrets.SLEEPER_LEAGUE }}
